# Generated by Django 4.0.4 on 2022-06-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ori_file',
        ),
    ]
