# Generated by Django 4.0.4 on 2022-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_image_ori_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ori_file',
            field=models.ImageField(default=1, upload_to='images/ori/'),
            preserve_default=False,
        ),
    ]
